name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    strategy:
      matrix:
        os: [ linux ]
        arch: [ 386, amd64, arm, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: Install dependencies
        run: go get .
      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: go build -o event-queue-worker-${{ matrix.os }}-${{ matrix.arch }} .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: event-queue-worker-${{ matrix.os }}-${{ matrix.arch }}